name: Terraform Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'deploy-*'
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage (e.g., dev, prod)'
        required: true
        default: dev

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="stage=${{ github.event.inputs.stage || 'dev' }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="stage=${{ github.event.inputs.stage || 'dev' }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

       - name: SSH to EC2 and run setup script (if needed)
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ steps.ec2.outputs.public_ip }}
           username: ubuntu
           key: ${{ secrets.EC2_PRIVATE_KEY }}
           script: |
            chmod +x setup.sh
             ./setup.sh

       - name: Health Check (App on Port 80)
         run: |
           curl -sSf http://${{ steps.ec2.outputs.public_ip }}:80 || exit 1
