name: Deploy Dev/Prod Infra

on:
  push:
    tags:
      - 'deploy-dev'
      - 'deploy-prod'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="stage=${{ github.ref_name == 'refs/tags/deploy-prod' && 'prod' || 'dev' }}" -var="bucket_name=tayyaba-devops-app-logs-techeazy"