name: Deploy Dev/Prod Infra

on:
  push:
    tags:
      - 'deploy-dev'
      - 'deploy-prod'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Determine Stage
      id: stage
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if [[ "$TAG_NAME" == "deploy-prod" ]]; then
          echo "stage=prod" >> "$GITHUB_OUTPUT"
        else
          echo "stage=dev" >> "$GITHUB_OUTPUT"
        fi

    - name: Terraform Apply (${{ steps.stage.outputs.stage }})
      run: |
        echo "Deploying to stage: ${{ steps.stage.outputs.stage }}"
        terraform apply -auto-approve \
          -var="stage=${{ steps.stage.outputs.stage }}" \
          -var="bucket_name=tayyaba-devops-app-logs-techeazy" \
          -var="github_token=${{ secrets.GH_PAT }}"
